[package]
name = "eden_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
eframe = "0.27.2"
egui = "0.27.2"
env_logger = "0.11.3"
log = "0.4.21"
